import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Layout from "./components/Layout"; 
import RouteLoadingSpinner from "./components/RouteLoadingSpinner";
import { Suspense } from "react";
import ReduxProvider from "./providers/ReduxProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <RouteLoadingSpinner /> */}
        <Suspense fallback={<RouteLoadingSpinner/>}>
          <ReduxProvider>
          <Layout>{children}</Layout>
          </ReduxProvider>
        </Suspense>
      </body>
    </html>
  );
}
